.TH edge 8  "5 Jan 2024" "version 3" "SUPERUSER COMMANDS"
.SH NAME
edge \- n3n edge node daemon
.SH SYNOPSIS
.B edge
[\fIoptions..\fR] [command] [\fIcommand args\fR]
.br
.B edge start
[\fIsessionname\fR] [\fB\-c \fR<\fIcommunity\fR>] [\fB\-l \fR<\fIsupernode host:port\fR>]
.br
.B edge --help
.SH DESCRIPTION
N3N is a peer-to-peer VPN system - it is the LAN you have when you have noLAN.

Edge is the edge node daemon for n3n which creates a TAP interface to expose
the n3n virtual LAN. On startup the edge will load any config file, then any
environment variables and then load the settings from the command line.

Once it has the full config loaded, it will registers with the supernode and
create and setup the TAP interface so it can
begin to find other nodes in the community.

See the CONFIG and EXAMPLE sections for the use of the config file.

.SH OPTIONS
Some of the most common options also have a shortcut version and you can see
all of them with:

.RS
.B edge help options
.RE
.TP
.SH Generic Options
.TP
\fB\-O \fR<\fIsection\fR>.<\fIoption\fR>=<\fIvalue\fR>
Sets any config option value.
.TP
\fB\-h\fR, \fB\--help\fR
Show some quick usage notes.
Options related to the network community being joined.
.TP
\fB\-c \fR<\fIcommunity\fR>, \fB\-\-community\fR=<\fIcommunity\fR>
sets the n3n community name (see also the ENVIRONMENT section). All edges
within the same community appear on the same LAN (layer 2 network segment).
Community name is 16 bytes in length. A name smaller than this is padded with
0x00 bytes and a name longer than this is truncated to take the first 16 bytes.
.TP
\fB\-l \fR<\fIhost:port\fR>, \fB\-\-supernode-list\fR=<\fIhost:port\fR>
sets the n3n supernode IP address and port to register to. Multiple supernodes
can be specified.
.TP
\fB\-k \fR<\fIkey\fR>
sets the encryption key from ASCII text (see also the ENVIRONMENT section). All
edges communicating must use the same key and community name. If a key is not
specified then edge uses cleartext mode (no encryption).
.TP
\fB\-A \fR<\fIcipher\fR>
choose a cipher for payload encryption, requires a key,
Twofish, AES (default if key provided),
ChaCha20, Speck
.TP
\fB\-z \fR<\fIcompresion\fR>
compress outgoing data packets. One of -z lzo, -z none
or -z zstd (if supported)
.TP
.SH TUNTAP Options
.TP
\fB\-a \fR[\fImode\fR]<\fIip\fR>[\fI/n\fR]
interface address and optional CIDR subnet, default '/24',
mode = [auto|static|dhcp]:, for DHCP use '\-r -a dhcp:0.0.0.0',
edge draws IP address from supernode if no '\-a ...' given
.TP
.SH FILTER Options
.TP
\fB\-r\fR
enable IP packet forwarding/routing through the n3n virtual LAN. Without this
option, IP packets arriving over n3n are dropped if not for the -a <addr> (or
DHCP assigned) IP address of the edge interface. This option is also required
to allow n3n device being used in network bridging, e.g. with brctl.
.TP
.SH DAEMON Options
.TP
\fB\-f\fR
do not fork and run as a daemon, rather run in foreground
.TP
\fB\-v\fR, \fB\-\-verbose\fR
make more verbose, repeat as required
.SH CONFIG FILE
When running the \fBstart\fR command, the edge will use the given sessionname
(Or "edge" if none is given) to search for a config file:

.RS
/etc/n3n/\fB<sessionname>\fR.conf

\fI%USERPROFILE%\fR\\n3n\\\fB<sessionname>\fR.conf (On Windows)
.RE

This file is an INI style file and a full description of the options is
available with the commandline:

.RS
.B edge help config
.RE
.SH ENVIRONMENT
After loading any config file, some settings are loaded from the environment.
(They can still be replaced by additional options from the commandline)

The environment variables are used so that the value is not not visible at the
command line.  It is expected that a config file will be better for most users.
.TP
.B N2N_KEY
set the encryption key (Equivalent to community.key, or -k)
.TP
.B N2N_COMMUNITY
set the community name (Equivalent to community.name, or -c)
.TP
.B N2N_PASSWORD
set the password for user-password authentication (Equivalent to auth.password)
.SH EXAMPLES
.TP
.SH Simplest example
.RE

For the simplest testing, without any encryption:

.RS
.B edge start -c mynetwork -l supernode.ntop.org:7777
.RE
.TP
.SH Config file example
.RE

Create a file \fB/etc/n3n/mynetwork.conf\fR with these contents:

.nf
.RS
[community]
name=mynetwork
key=mypassword
supernode=supernode.ntop.org:7777
.RE
.fi

Then start the daemon in the foreground:

.RS
.B edge start mynetwork -f
.RE

.TP
.SH Complex example

.nf
.B edge start \\\\
    \-O tuntap.name=n3n0 \\
    \-c mynetwork \\
    \-k encryptme \\
    \-O daemon.userid=99 \\
    \-O daemon.groupid=99 \\
    \-O tuntap.macaddr=DE:AD:BE:EF:01:23 \\
    \-a 192.168.254.7 \\
    \-O connection.bind=50001 \\
    \-l 123.121.120.119:7654
.fi

Starts edge with TAP device n3n0 on community "mynetwork" with community
supernode at 123.121.120.119 UDP port 7654 and bind the locally used UDP port to
50001. Use "encryptme" as the single permanent shared encryption key. Assign MAC
address DE:AD:BE:EF:01:23 to the n3n interface and drop to user=99 and group=99
after the TAP device is successfully configured.

(Add the -f option to stop edge running as a daemon)

On a second computer setup another edge with similar parameters, eg:

.nf
.B edge \\\\
    \-O tuntap.name=n3n0 \\
    \-c mynetwork \\
    \-k encryptme \\
    \-O daemon.userid=99 \\
    \-O daemon.groupid=99 \\
    \-O tuntap.macaddr=DE:AD:BE:EF:01:21 \\
    \-a 192.168.254.5 \\
    \-O connection.bind=50001 \\
    \-l 123.121.120.119:7654
.fi

Now you can ping from 192.168.254.5 to 192.168.254.7.

The MAC address (tuntap.macaddr) and virtual IP address (-a <addr>) must be
different on all edges in the same community.

.SH CLEARTEXT MODE
If
.B -k
is not specified then edge uses cleartext mode. In cleartext mode there is no
transform of the packet data it is simply encrypted. This is useful for
debugging n3n as packet contents can be seen clearly.

To prevent accidental exposure of data, edge only enters cleartext mode when no
keying parameters are specified. In the case where keying parameters are
specified but no valid keys can be determined, edge exits with an error at
startup. If all keys become invalid while running, edge continues to encode
using the last key that was valid.

.SH MANAGEMENT INTERFACE
Edge always provides JsonAPI listening on a Unix Domain socket in /run/n3n and
optionally a TCP port (if configured with the management.port option)
See the docs/ManagementAPI.md for details.

.SH EXIT STATUS
When edge is run as a daemon, any exit is an error.  In other cases, the exit
status will be 0 for no issues found.
.SH AUTHORS
.TP
Hamish Coleman
hamish (at) zot.org - n3n maintainer
.TP
Richard Andrews
andrews (at) ntop.org - n2n-1 maintainer and main author of n2n-2
.TP
Luca Deri
deri (at) ntop.org - original author of n2n
.TP
Don Bindner
(--) - significant contributions to n2n-1
.SH SEE ALSO
ifconfig(8) supernode(1) tunctl(8) n3n(7)
.br
the documentation contained in the source code
.br
the extensive documentation found in n3n's \fBdoc/\fR folder
