---

site_name: 'n3n: A peer-to-peer VPN'
theme: readthedocs

repo_url: https://github.com/n42n/n3n
edit_uri: https://github.com/n42n/n3n/blob/main/docs/

use_directory_urls: false

nav:
  - Home: README.md
  - Licensing: Licensing.md
  - Quick Start Guides:
      - Config: quick_start/Config.md
      - Debian: quick_start/Debian.md
  - Links:
      - Bug Tracker: 'https://github.com/n42n/n3n/issues'
