#!/usr/bin/env python3
"""Send and recieve test packets"""
#
# Copyright (C) 2024 Hamish Coleman
# SPDX-License-Identifier: GPL-2.0-only

import argparse
import pprint
import socket
import struct


def hexdump(display_addr, data):
    size = len(data)

    row = 0
    while size > 0:
        print(f"{display_addr:03x}: ", end="")

        for i in range(16):
            if i < size:
                print(f"{data[row+i]:02x}", end="")
            else:
                print("  ", end="")

            if i == 7:
                print(" ", end="")
            print(" ", end="")

        print("  |", end="")

        for i in range(16):
            if i < size:
                ch = data[row+i]
                if ch >= 0x20 and ch <= 0x7e:
                    print(chr(ch), end="")
                else:
                    print(" ", end="")

        print("|")

        size -= 16
        display_addr += 16
        row += 16


class PacketBase():
    names = [
        None,
        "REGISTER",             # 1
        "DEREGISTER",           # this packet never used in original code
        "PACKET",
        "REGISTER_ACK",
        "REGISTER_SUPER",       # 5
        "UNREGISTER_SUPER",
        "REGISTER_SUPER_ACK",
        "REGISTER_SUPER_NAK",
        "FEDERATION",
        "PEER_INFO",            # 10
        "QUERY_PEER",
        "RE_REGISTER_SUPER",
    ]

    @classmethod
    def id2type(cls, id):
        return cls.names[id]

    @classmethod
    def type2id(cls, name):
        return cls.names.index(name)

    defaults = {
        "proto_version": 3,
        "ttl": 2,
        "flags": 0,
        "community": b"test",
        "cookie": 0x1000,
        "srcMac": b"\x00\x00\x00\x00\x00\x01",
        "dstMac": b"\x00\x00\x00\x00\x00\x02",
        "edgeMac": b"\x00\x00\x00\x00\x00\x03",
        "targetMac": b"\x00\x00\x00\x00\x00\x04",
        "ipv4": b"\x00\x00\x00\x00",
        "masklen": 0,
        "desc": b"packetgenerator",
        "auth_scheme": 0,   # n2n_auth_none
        "auth_token_size": 0,
        "auth_token": b"",
        "key_time": 600,
        "aflags": 0,
        "compression": 1,   # COMPRESSION_ID_NONE
        "transform": 1,     # TRANSFORM_ID_NULL
        "packet": b"\x02\x00\x00\x00\x00\x11"
                  b"\x02\x00\x00\x00\x00\x22"
                  b"\x0f\x0f"
                  b"\x55\xaa",
        "sock_family": socket.AF_INET,
        "sock_port": 8000,
        "sock_addr": b"\x01\x02\x03\x04",
    }

    @classmethod
    def set_default(cls, key, val):
        cls.defaults[key] = val

    @classmethod
    def get_default(cls, key):
        return cls.defaults[key]

    def __init__(self, scenario=None):
        # Set the default values for all the field data
        self.data = self.defaults.copy()
        self.buffer = None
        self.unstable_fields = {}
        self._init_format(scenario)

    def _init_format(self, scenario):
        """Remove this after the specific object classes conversion"""
        pass

    def encode_common(self):
        """Return a buffer with just the common header fields"""
        if "type" not in self.data:
            raise ValueError("Unknown packet type")

        # special case for this one field
        type_flags = self.data["type"] & 0x1f
        type_flags |= self.data["flags"] & 0xffe0

        return struct.pack(
            "!BBH20s",
            self.data["proto_version"],
            self.data["ttl"],
            type_flags,
            self.data["community"]
        )

    def decode_common(self):
        """Update our data with just the common fields"""
        data = struct.unpack("!BBH20s", self.buffer[:24])
        pkt_type = data[2] & 0x1f

        try:
            self.data["_name"] = self.id2type(pkt_type)
        except IndexError:
            pass

        self.data["proto_version"] = data[0]
        self.data["ttl"] = data[1]
        self.data["type"] = pkt_type
        self.data["flags"] = data[2] & 0xffe0
        self.data["community"] = data[3]

    def encode_sock(self):
        # TODO: sock->type == SOCK_STREAM
        if self.data["sock_family"] == socket.AF_INET:
            format = "!HH4s"
        elif self.data["sock_family"] == socket.AF_INET6:
            format = "!HH16s"
        else:
            raise ValueError("Unknown sock_family")

        return struct.pack(
            format,
            0,
            self.data["sock_port"],
            self.data["sock_addr"],
        )

    def decode_sock(self, buffer):
        # TODO: sock->type == SOCK_STREAM

        data = struct.unpack("!H", buffer[:2])
        family = data[0] & 0x8000
        if family == 0:
            self.data["sock_family"] = socket.AF_INET
            format = "!HH4s"
        elif family == 0x8000:
            self.data["sock_family"] = socket.AF_INET6
            format = "!HH16s"
        else:
            raise ValueError(f"Unknown sock_family {data[0]}")

        calcsize = struct.calcsize(format)
        buffer = buffer[:calcsize]

        data = struct.unpack(format, buffer)
        self.data["sock_port"] = data[1]
        self.data["sock_addr"] = data[2]
        return calcsize

    def encode(self):
        common = self.encode_common()

        fielddata = [self.data[f] for f in self.fields]
        specific = struct.pack(self.format, *fielddata)

        self.buffer = common + specific
        return self.buffer

    def decode(self, buffer):
        self.buffer = buffer
        self.data = {}

        # first, get the common header
        self.decode_common()

        # now, turn ourselves into that type
        self._init_format(self.data["type"])

        if "_name" not in self.data:
            # probably header encrypted
            return self.data

        formatstr, buffer = self._decode_prep(buffer)

        if not formatstr:
            # No known decoding to do
            return self.data

        # finally, decode the specific fields

        data = struct.unpack(formatstr, buffer)

        for i in range(len(data)):
            key = self.fields[i]
            val = data[i]
            self.data[key] = val

        return self.data

    def _decode_prep(self, buffer):
        """Perform as much as possible of the shared work for decoding"""
        self.buffer = buffer
        self.data = {}

        # first, get the common header
        self.decode_common()

        # Remove the header from our working data
        buffer = buffer[24:]

        if "format" not in self.__dict__:
            # no struct format string for this struct
            return "", buffer

        formatstr = self.format
        calcsize = struct.calcsize(formatstr)
        if len(buffer) > calcsize:
            # dont abort on to many bytes, simply ignore them all
            formatstr += f"{len(buffer) - calcsize}x"
        if len(buffer) < calcsize:
            print(f"buffer: {len(buffer)}")
            print(f"calcsize: {calcsize}")
            print(f"format: {formatstr}")
            raise ValueError("buf too small")

        return formatstr, buffer

    def stable_values(self):
        """Remove fields that will constantly change - allowing testing"""

        changed = False
        for field, val in self.unstable_fields.items():
            self.data[field] = val
            changed = True

        if changed and self.buffer is not None:
            self.encode()

    def flags_socket(self):
        return self.data["flags"] & 0x0040


class PacketREGISTER(PacketBase):
    format1 = "!I6s6s"
    format2 = "!4sB16s"

    def encode(self):
        self.data["type"] = 1

        common = self.encode_common()
        specific1 = struct.pack(
            self.format1,
            self.data["cookie"],
            self.data["srcMac"],
            self.data["edgeMac"],
        )

        if self.flags_socket():
            sock = self.encode_sock()
        else:
            sock = b""

        specific2 = struct.pack(
            self.format2,
            self.data["ipv4"],
            self.data["masklen"],
            self.data["desc"],
        )

        self.buffer = common + specific1 + sock + specific2
        return self.buffer

    def decode(self, buffer):
        _, buffer = self._decode_prep(buffer)

        calcsize1 = struct.calcsize(self.format1)
        buffer1 = buffer[:calcsize1]
        buffer2 = buffer[calcsize1:]
        data = struct.unpack(self.format1, buffer1)
        self.data["cookie"] = data[0]
        self.data["srcMac"] = data[1]
        self.data["edgeMac"] = data[2]

        if self.flags_socket():
            size2 = self.decode_sock(buffer2)
            buffer2 = buffer2[size2:]

        data = struct.unpack(self.format2, buffer2)
        self.data["ipv4"] = data[0]
        self.data["masklen"] = data[1]
        self.data["desc"] = data[2]

        return self.data


class PacketGeneric(PacketBase):
    specific = {
        1: PacketREGISTER,
    }

    @classmethod
    def from_buffer(cls, buffer):
        obj = PacketGeneric()
        obj.buffer = buffer
        obj.decode_common()
        pkt_type = obj.data["type"]
        if pkt_type in cls.specific:
            obj = cls.specific[pkt_type]()

        obj.decode(buffer)
        return obj

    @classmethod
    def from_scenario(cls, scenario):
        if scenario not in cls.types:
            raise ValueError("Unknown scenario")
        if "class" in cls.types[scenario]:
            return cls.types[scenario]["class"]()

        return PacketGeneric(scenario)

    types = {
        "test_REGISTER": {
            "class": PacketREGISTER,
        },
        # 1:
        #   TODO
        #   - the test_REGISTER scenario causes the packet to be forwarded
        #   - the forwarded version has the optional sock added
        #   - so we want a way to share the frame definition, but support
        #     the optional sock :-(
        "test_PACKET": {
            "data": {
                "type": 3,
            },
            "format": "!6s6sBB64s",
            "fields": [
                "srcMac",
                "edgeMac",
                # TODO? Optional sock
                "compression",
                "transform",
                "packet",
            ],
        },
        "test_REGISTER_SUPER": {
            "data": {
                "type": 5,
            },
            "format": "!I6s4sB16sHHL",
            "fields": [
                "cookie",
                "edgeMac",
                # TODO? Optional sock
                "ipv4",
                "masklen",
                "desc",
                "auth_scheme",
                "auth_token_size",
                # "auth_token" if token_size
                "key_time",
            ],
        },
        "test_UNREGISTER_SUPER": {
            "data": {
                "type": 6,
            },
            "format": "!HH6s",
            "fields": [
                "auth_scheme",
                "auth_token_size",
                # "auth_token" if token_size
                "edgeMac",
            ],
        },
        7: {
            "format": "!I6s4sBHHH4sHHB",
            "fields": [
                "cookie",
                "srcMac",
                "ipv4",
                "masklen",
                "lifetime",
                "sock_flag",
                "sock_port",
                "sock_v4",      # FIXME - variable size, based on sock_flag
                "auth_scheme",
                "auth_token_size",
                # "auth_token",   # FIXME - variable size, based on token_size
                "num_sn",
                # TODO: SN buf
            ],
        },
        10: {
            "format": "!H6s6sHH4sLL20s",
            "fields": [
                "aflags",
                "srcMac",
                "mac",
                "sock_flag",
                "sock_port",
                "sock_v4",      # FIXME - variable size, based on sock_flag
                # TODO: optional preferred_sock
                "load",
                "uptime",
                "version",
            ],
            "unstable_fields": {
                "load": 0xffffffff,
                "uptime": 0xffffffff,
                "version": b"_stabilised_",
            },
        },
        "test_QUERY_PEER": {
            "data": {
                "type": 11,
            },
            "format": "!6s6sH",
            "fields": [
                "srcMac",
                "edgeMac",
                "aflags",
            ],
        },
        "test_QUERY_PEER_ping": {
            "data": {
                "type": 11,
                "targetMac": b"\x00\x00\x00\x00\x00\x00",
            },
            "format": "!6s6sH",
            "fields": [
                "srcMac",
                "targetMac",
                "aflags",
            ],
        }
    }

    def _init_format(self, scenario):
        if scenario is None:
            return
        if scenario not in self.types:
            return

        if "data" in self.types[scenario]:
            self.data.update(self.types[scenario]["data"])
        self.format = self.types[scenario]["format"]
        self.fields = self.types[scenario]["fields"]
        if "unstable_fields" in self.types[scenario]:
            self.unstable_fields = self.types[scenario]["unstable_fields"]


# to supernode:
# - PACKET -> forwarded to another node
# - REGISTER -> forwarded
# - REGISTER_SUPER -> REGISTER_SUPER_NAK or REGISTER_SUPER_ACK and/or forwarded
# - UNREGISTER_SUPER -> deletes peer, no reply
# - QUERY_PEER -> PEER_INFO
# - PEER_INFO -> forwarded

# to edge:
# - PACKET -> processed to tun
# - REGISTER -> if !from_supernode, REGISTER_ACK
# - PEER_INFO -> REGISTER
# - RE_REGISTER_SUPER -> REGISTER_SUPER , multicast REGISTER


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "-s",
        "--server",
        help="host and port of server to contact",
        default="localhost:1968"
    )
    ap.add_argument(
        "--bind",
        help="bind local socket to port",
        type=int,
        default=False
    )
    ap.add_argument(
        "-c",
        "--community",
        help="The n3n community name",
        default="test"
    )
    ap.add_argument(
        "-t",
        "--timeout",
        type=int,
        help="how long to wait for replies",
        default=10
    )
    ap.add_argument(
        "--raw",
        help="Dont stablise the results - show the real data",
        default=False
    )
    ap.add_argument("scenario", help="What packet to send")

    args = ap.parse_args()

    host, sep, port = args.server.partition(":")
    port = int(port)

    community = args.community.encode("utf8")
    PacketBase.set_default("community", community)

    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.settimeout(args.timeout)
    if args.bind:
        sock.bind(('', args.bind))

    if args.scenario != "listen":
        send_pkt = PacketGeneric.from_scenario(args.scenario)
        buf = send_pkt.encode()
        print("test:")
        hexdump(0, buf)

        sock.sendto(buf, (host, port))

    if args.timeout == 0:
        return

    data = sock.recv(1600)

    recv_pkt = PacketGeneric.from_buffer(data)
    recv_pkt.decode(data)

    if not args.raw:
        recv_pkt.stable_values()

    print("recv:")
    hexdump(0, recv_pkt.buffer)
    pprint.pp(recv_pkt.data)


if __name__ == '__main__':
    main()
